Add optional chaining to author in teaser posts list
vtex-apps/wordpress-integration pull request #120
Opened 2022-05-30 22:10 UTC by santiagoalex

Added optional chaining to the author in teaser posts list to prevent fall application because it is possible to posts that don't have an author

**What problem is this solving?**
There is a breakdown in the application when listing category teasers and this does have the author in posts

![Error_teaser_no_existe_author](https://user-images.githubusercontent.com/19352507/171062455-07648a8f-a38d-499e-9f24-3593bc357520.png)

**How should this be manually tested?**

Install this branch in your workspace and use a WordPress that doesn´t  have authors in posts

**Screenshots or example usage:**

Install this versión in your workspace by typing `vtex install` in your root project

2022-05-30 22:58 UTC, santiagoalex commented
> Hi! I'm VTEX IO CI/CD Bot and I'll be helping you to publish your app! robot
> 
> Please select which version do you want to release:
> 
> * [x]  Patch (backwards-compatible bug fixes)
> * [ ]  Minor (backwards-compatible functionality)
> * [ ]  Major (incompatible API changes)
> 
> And then you just need to merge your PR when you are ready! There is **no need** to create a release commit/tag.
> 
> * [ ]  No thanks, I would rather do it manually disappointed

2022-05-30 22:59 UTC, santiagoalex commented
> Beep boop robot
> 
> I noticed you didn't make any changes at the `docs/` folder
> 
> * [x]  There's nothing new to document thinking
> * [ ]  I'll do it later disappointed
> 
> In order to keep track, I'll create an issue if you decide now is not a good time
> 
> * [ ]  I just updated tadatada

2022-06-30 14:32 UTC, santiagoalex commented
Good morning @Syed-Vtex, I hope you are okay.

it would help a lot if this PR could be reviewed, it would prevent render issues from the app on the categories  page

2022-06-30 14:58 UTC, polishq requested changes

2022-06-30 14:58 UTC, polishq commented on CHANGELOG.md
> +## [2.19.3] - 2022-05-30
Please remove this `2.19.3` entry and move your `Fixed` item up into the `Unreleased` section at the top of the changelog. It should look like this:

```
## [Unreleased]

### Fixed

- Add conditional ...

## [2.20.0] - 2022-06-22

### Added
...
```

2022-06-30 14:58 UTC, polishq commented on manifest.json
> +  "version": "2.20.1",
Do not change the version number; a GitHub bot will do this automatically when the PR is merged

2022-07-01 13:21 UTC, santiagoalex commented on CHANGELOG.md
> +## [2.19.3] - 2022-05-30
Thanks a lot for your feedback!

2022-07-01 14:13 UTC, polishq requested changes

2022-07-01 14:13 UTC, polishq commented on react/components/WordpressCategory.tsx
> +export default WordpressCategory
Add a new line at the end of this file to fix the lint error

2022-07-01 17:04 UTC, merged