Added CSS Handle for image container (on Link)
vtex-apps/wordpress-integration pull request #58
Opened 2021-01-27 10:05 UTC by razvanudream

**What problem is this solving?**

This adds a CSS handle on the Link that wraps the image of a related article.   It is needed to customize the how the 3 elements inside the main vtex-card are displayed.   We can't use display grid on them without a class on each child.

**How should this be manually tested?**

New version linked on https://razvanudream--fstudio.myvtex.com/ (which is a dev environment) OR can be seen here
![image](https://user-images.githubusercontent.com/71461884/105975450-a3d67080-6097-11eb-8d74-7fd8ec43cd90.png)

2021-01-27 14:22 UTC, polishq approved these changes

2021-02-03 14:11 UTC, polishq requested changes
Please rebase this branch as there have been further releases since it was created.

Also, please update CHANGELOG.md.

2021-02-03 14:33 UTC, razvanudream commented
> Please rebase this branch as there have been further releases since it was created.
> 
> Also, please update CHANGELOG.md.

Done and done. 

Cheers

2021-02-03 14:42 UTC, polishq approved these changes

2021-02-03 15:29 UTC, merged