fix(blog): change post idiom
vtex-apps/wordpress-integration pull request #74
Opened 2021-05-25 15:37 UTC by LucasSavoia

**What problem is this solving?**
The posts were with other language, and we need it in portuguese.

**How should this be manually tested?**

**Screenshots or example usage:**
![image](https://user-images.githubusercontent.com/55500373/119526648-f37f2d00-bd55-11eb-9d66-d23432598724.png)

2021-05-25 16:49 UTC, LucasSavoia commented
> Hi! I'm VTEX IO CI/CD Bot and I'll be helping you to publish your app! 🤖
> 
> Please select which version do you want to release:
> 
> * [x]  Patch (backwards-compatible bug fixes)
> * [ ]  Minor (backwards-compatible functionality)
> * [ ]  Major (incompatible API changes)
> 
> And then you just need to merge your PR when you are ready! There is **no need** to create a release commit/tag.
> 
> * [ ]  No thanks, I would rather do it manually 😞

2021-05-25 16:50 UTC, LucasSavoia commented
> Beep boop 🤖
> 
> I noticed you didn't make any changes at the `docs/` folder
> 
> * [x]  There's nothing new to document 🤔
> * [ ]  I'll do it later 😞
> 
> In order to keep track, I'll create an issue if you decide now is not a good time
> 
> * [ ]  I just updated 🎉🎉

2021-06-01 22:38 UTC, SDBowen requested changes
@LucasSavoia thanks for the PR!

Seems we lost some spacing. Should be able to add it to the translation messages.

![Screenshot from 2021-06-01 18-19-51](https://user-images.githubusercontent.com/22715037/120398108-97914700-c307-11eb-9a35-e7c8de5f7b53.png)

2021-06-01 22:38 UTC, SDBowen commented on react/components/WordpressPage.tsx
> +            <formattedMessage
`FormattedMessage`

and needs the import.

2021-06-01 22:38 UTC, SDBowen commented on react/components/WordpressPost.tsx
> +              defaultMessage="Posted {formattedDate} by"
"Posted {formattedDate} **in** "

2021-06-01 22:38 UTC, SDBowen commented on messages/en.json
> +  "store/wordpress-integration.wordpressPage.byAuthor": "by {name}"
"Posted {formattedDate} **in** "
" by {name}"
"Posted {formattedDate} "
" by {name}"

2021-06-04 14:15 UTC, SDBowen approved these changes

2021-06-04 14:15 UTC, merged