Feature/subcategory url
vtex-apps/wordpress-integration pull request #76
Opened 2021-06-04 13:28 UTC by SDBowen

**What problem is this solving?**

Adds the option to include a subcategory in the blog URLs, `/blog/category/subcategory`. This can improve user navigation within the blog content and improve SEO.   

**How should this be manually tested?**

[workspace with subcategory URLs enabled](https://wpsubcategory--arcaplanet.myvtex.com)
[workspace without subcategory URLs enabled](https://sdb--arcaplanet.myvtex.com)

**Screenshots or example usage:**

![Screenshot from 2021-06-04 09-27-05](https://user-images.githubusercontent.com/22715037/120808531-27f1a680-c517-11eb-99a2-3555addb13dc.png)

2021-06-08 13:56 UTC, polishq requested changes

2021-06-08 13:56 UTC, polishq commented on docs/README.md
> +To have subcategories included in your blog URLs (`/blog/category/subcategory`), you will need to update your stres's `routes.json`, as well as the theme's blocks that display category-related URLs.
```suggestion
To have subcategories included in your blog URLs (`/blog/category/subcategory`), you will need to update your store's `routes.json`, as well as the theme's blocks that display category-related URLs.
```

2021-06-08 13:56 UTC, polishq commented on docs/README.md
> +	"path": "/blog/category/:categoryslug_id(/:subcategoryslug)"
This just occurred to me -- param should probably be `subcategoryslug_id` to enable the site editor to target individual subcategories. Do we know if there's any problem using multiple `_id` params in the same route?

2021-06-08 13:56 UTC, polishq commented on react/components/WordpressCategoryBlock.tsx
> +  category: catgoryId,
```suggestion
  category: categoryId,

```

2021-06-08 13:56 UTC, polishq commented on react/components/WordpressCategoryBlock.tsx
> +      category: catgoryId,
```suggestion
      category: categoryId,

```

2021-06-08 13:56 UTC, polishq commented on react/components/WordpressCategoryBlock.tsx
> +              params={buildCatelogParams()}
```suggestion
              params={buildCatalogParams()}

```

2021-06-08 13:56 UTC, polishq commented on react/components/WordpressPost.tsx
> +  const buildCatelogParams = (category: WPCategory) => {
```suggestion
  const buildCatalogParams = (category: WPCategory) => {

```

2021-06-08 13:56 UTC, polishq commented on react/components/WordpressPost.tsx
> +                  params={buildCatelogParams(cat)}
```suggestion
                  params={buildCatalogParams(cat)}

```

2021-06-08 16:08 UTC, SDBowen commented on docs/README.md
> +	"path": "/blog/category/:categoryslug_id(/:subcategoryslug)"
Without the `_id`, is the page expected to not be reachable?

Playing around with the site editor, I can reach a blog subcategory page regardless of having the `_id` identifier. Both versions are acting the same for me.

2021-06-08 17:09 UTC, polishq commented on docs/README.md
> +	"path": "/blog/category/:categoryslug_id(/:subcategoryslug)"
I think the idea is that the `_id` allows a specific instance of a dynamic route to be targetable. For example if you wanted a banner to appear only on /blog/some-category/some-specific-subcategory . Whereas if the `_id` is left off, the site editor is only able to add a banner that will appear on ALL subcategory pages.

2021-06-08 17:11 UTC, polishq commented on docs/README.md
> +	"path": "/blog/category/:categoryslug_id(/:subcategoryslug)"
See https://github.com/vtex-apps/wordpress-integration/pull/49

2021-06-11 14:04 UTC, polishq requested changes

2021-06-11 18:10 UTC, polishq approved these changes

2021-06-11 18:15 UTC, merged